version: "3.4"
services:
  db:  #CONTAINER MYSQL - Este nome é preferencial
    image: mysql:5.7.22 #É SIMILAR AO FROM PARA CRIAR IMAGEM
    command: mysqld --default_authentication_plugin=mysql_native_password 
    environment: #criação da minhas variaveis de ambiente
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: saulo
      MYSQL_USER: saulo
      MYSQL_PASSWORD: saulo
      MYSQL_DATABASE: wordpress
    ports:
      - 3308:3306
    networks:
      - wordpress-network
  wordpress: #inicio outro container- Este nome é preferencial    
    image: wordpress:latest
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html  
    environment:
      TZ: America/Sao_Paulo
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: saulo  
    ports:
      - "80:80"   #aqui informamos que 8000 do meu pc e 80 no para porta de configuração
    networks:
      - wordpress-network
networks:
    wordpress-network:
      driver: bridge